version: '3.1'

services:
  api_report:
    restart: always
    container_name: api_report
    build:
      context: .
    command: /bin/sh -c "go run main.go"
    stdin_open: true
    tty: true
    volumes:
      - .:/app
      - /opt/certs:/certs:ro    # Sertifikat HTTPS dimount read-only

    ports:
      - 2366:2345
    networks:
      - shared_network
    env_file:
      - .env

networks:
  shared_network:
    external: true